version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: .config/sta/app.dockerfile
    working_dir: /var/www/sta
    volumes:
      - ./:/var/www/staging
    environment:
      - "DB_PORT=3307"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: .config/dev/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 81:80
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports: 
      - "33062:3306"
volumes:
  dbdata: