version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: .config/dev/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: .config/dev/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
      - 443:443
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports: 
      - "33061:3306"
volumes:
  dbdata: